# Generated by Django 3.1.7 on 2021-05-30 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OF', 'Offensive'), ('DE', 'Defensive'), ('HE', 'Healing'), ('MA', 'Magic')], max_length=50)),
                ('range', models.CharField(choices=[('LO', 'Low Range'), ('ME', 'Medium Range'), ('LN', 'Long Range')], max_length=50)),
                ('origin', models.CharField(choices=[('CD', 'Chest Drop'), ('BD', 'Boss Drop'), ('SH', 'Shop'), ('CR', 'Crafting')], max_length=50)),
                ('craftable', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField()),
                ('champ_class', models.CharField(choices=[('MA', 'Mage'), ('WA', 'Warrior'), ('HE', 'Healer'), ('TA', 'Tank')], max_length=50)),
                ('guild', models.CharField(choices=[('OR', 'Orc'), ('HU', 'Human'), ('EL', 'Elf')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('CO', 'Common'), ('UN', 'Uncommon'), ('RA', 'Rare'), ('EP', 'Epic'), ('LE', 'Legendary')], max_length=50)),
                ('wear', models.CharField(choices=[('NE', 'New'), ('SW', 'Slightly Worn'), ('HW', 'Heavily Worn'), ('DE', 'Destroyed')], max_length=50)),
                ('damage', models.PositiveIntegerField()),
                ('damage_blocked', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=0, max_digits=6)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.champion')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.property'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.shop'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.update')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('cooldown', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
